# Generated by Django 4.0.5 on 2022-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('trade_code', models.CharField(max_length=200)),
                ('high', models.CharField(max_length=200)),
                ('low', models.CharField(max_length=200)),
                ('open', models.CharField(max_length=200)),
                ('close', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
            ],
        ),
    ]
